#!/bin/bash -l

function buildBinary(){
  mkdir $(pwd)/releases
  #$DOCKERBIN run --rm -it --privileged -e MKPKG_VER=${VERSION} -v $(pwd)/repo:/root/repo  -v $(pwd)/source:/opt/wine-electrum/drive_c/tate/ mazaclub/tate-winbuild /root/make_release $VERSION
  $DOCKERBIN run --rm -it --privileged -e MKPKG_VER=${VERSION} -v $(pwd)/repo:/root/repo  -v $(pwd)/source:/opt/wine-electrum/drive_c/tate/ mazaclub/tate-winbuild /bin/bash
  if [[ $? = 0 ]]; then
    echo "Build successful."
  else
    echo "Seems like the build failed. Exiting."
    exit
  fi
  mkdir -pv $(pwd)/releases 
  cp $TARGETFOLDER/dist/tate.exe $(pwd)/releases/Tate-$VERSION.exe
  cp $(pwd)/source/tate-setup.exe $(pwd)/releases/Tate-$VERSION-setup.exe
  cp $(pwd)/repo/dist/* $(pwd)/releases/
  if [ "${TYPE}" = "SIGNED" ] ; then
    cd releases
    for release in * 
    do
      sha1sum ${release} > ${release}.sha1
      md5sum ${release} > ${release}.md5
      gpg --sign --armor --detach  ${release}
      gpg --sign --armor --detach  ${release}.md5
      gpg --sign --armor --detach  ${release}.sha1
    done
  fi
  echo "You can find your Tate $VERSION binaries in the releases folder."

}

function buildImage(){
  echo "Building image"
  $DOCKERBIN build -t mazaclub/tate-winbuild .
}
function buildLtcScrypt() {
## this will be integrated into the main build in a later release
   wget https://pypi.python.org/packages/source/l/ltc_scrypt/ltc_scrypt-1.0.tar.gz
   tar -xpzvf ltc_scrypt-1.0.tar.gz 
   echo "Building Windows binary ltc_scrypt.pyd"
   docker run -it --rm \
    -e WINEPREFIX="/wine/wine-py2.7.8-32" \
    -v $(pwd)/ltc_scrypt-1.0:/code \
    -v $(pwd)/helpers:/helpers \
    ogrisel/python-winbuilder wineconsole --backend=curses  Z:\\helpers\\ltc_scrypt-build.bat
   cp -v ltc_scrypt-1.0/build/lib.win32-2.7/ltc_scrypt.pyd helpers/ltc_scrypt.pyd
   echo "Building ltc_scrypt module for OSX"
   docker run -it --rm \
    -e LDFLAGS="-L/usr/x86_64-apple-darwin14/SDK/MacOSX10.10.sdk/usr/lib/ -L/usr/x86_64-apple-darwin14/lib -L/usr/x86_64-apple-darwin14/SDK/MacOSX10.10.sdk/usr/libexec/" \
    -e PYTHONXCPREFIX="/usr/x86_64-apple-darwin14/" \
    -e MAC_SDK_VERSION="10.10" \
    -e LD_LIBRARY_PATH="/usr/lib/llvm-3.4/lib:/usr/x86_64-apple-darwin14/lib" \
    -e PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/x86_64-apple-darwin14/bin" \
    -e CROSS_TRIPLE="x86_64-apple-darwin14" \
    -e LDSHARED="x86_64-apple-darwin14-cc -shared" \
    -e CROSS_ROOT="/usr/x86_64-apple-darwin14" \
    -e CC="x86_64-apple-darwin14-cc" \
    -e CROSS_COMPILE="x86_64-apple-darwin14-" \
    -v $(pwd):/code \
    -v $(pwd)/helpers/build-darwin-ltc_scrypt.sh:/build-darwin-ltc_scrypt.sh \
    mazaclub/cross-compiler:darwin-x64 /build-darwin-ltc_scrypt.sh
    cp -v ltc_scrypt-1.0/build/lib.darwin-x64/ltc_scrypt.dylib helpers/ltc_scrypt.dylib
}

function prepareFile(){
  echo "Preparing file for Tate version $VERSION"
  if [ -e "$TARGETPATH" ]; then
    echo "Version tar already downloaded."
  else
   wget https://github.com/mazaclub/tate/archive/v${VERSION}.zip -O $TARGETPATH
  fi

  if [ -d "$TARGETFOLDER" ]; then
    echo "Version is already extracted"
  else
     unzip -d $(pwd)/source ${TARGETPATH} 
   # tar -xvf $TARGETPATH -C $(pwd)/source
  fi
}

if [[ $# -gt 0 ]]; then
  VERSION=$1
  TYPE=$2
  FILENAME=Tate-$VERSION.zip
  TARGETPATH=$(pwd)/source/$FILENAME
  TARGETFOLDER=$(pwd)/source/Tate-$VERSION
  echo "Building Tate $VERSION from $FILENAME"
else
  echo "Usage: ./build <version>."
  echo "For example: ./build 1.9.8"
  exit
fi

which docker
if [[ $? = 0 ]]; then
  DOCKERBIN=$(which docker)
fi

which docker.io
if [[ $? = 0 ]]; then
  DOCKERBIN=$(which docker.io)
fi

if [[ -z "$DOCKERBIN" ]]; then
        echo "Could not find docker binary, exiting"
        exit
else
        echo "Using docker at $DOCKERBIN"
fi

buildLtcScrypt
# Build docker image
buildImage

# Prepare host file system
#prepareFile

# Build files
buildBinary
