#!/bin/bash

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/tate/Tate-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/tate/deterministic.spec"
cp /opt/wine-electrum/drive_c/tate/tate.nsi $SOURCEDIR/

echo "Running c:/tate/Tate-$VERSION/tate.nsi for install"
xvfb-run wine c:\\"Program Files (x86)"\\NSIS\\makensis.exe -V1 c:/tate/Tate-$VERSION/tate.nsi


cleanup
