#!/bin/bash -x
VERSION="$1"
echo "Making packages"
mkdir -pv /root/repo
git clone https://github.com/mazaclub/tate /root/repo
cd /root/repo
git checkout v$VERSION
cp -v  /root/make_packages /root/repo/make_packages
cd /root/repo
mkdir ./packages
./make_packages
## rm just isn't that expensive to run without fancy bash expansions

rm -rf /opt/wine-electrum/drive_c/tate/Tate-$VERSION.*
rm -rf /opt/wine-electrum/drive_c/tate/Tate-$VERSION/
rm -rf /opt/wine-electrum/drive_c/tate/tate-$VERSION/

cp -v /root/repo/dist/Tate-$VERSION.zip /opt/wine-electrum/drive_c/tate
cd /opt/wine-electrum/drive_c/tate
unzip Tate-$VERSION.zip
cp -a /root/ltc_scrypt.pyd /opt/wine-electrum/drive_c/tate/Tate-$VERSION/lib/chains

/usr/bin/build-binary $VERSION
